# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_registered'),
        ),
    ]
