# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('vram', models.IntegerField(default=8000)),
                ('core_clock', models.IntegerField(default=1500)),
                ('memory_clock', models.IntegerField(default=4000)),
                ('watts', models.IntegerField(default=500)),
                ('ram_memory', models.CharField(default='GDDR4', max_length=10)),
            ],
            bases=('products.product',),
        ),
    ]
