# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('product_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('brand', models.CharField(default='NoName', max_length=20)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=10)),
                ('total_rating', models.IntegerField(default=11)),
            ],
        ),
    ]
