# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('memory', models.IntegerField(default='8')),
                ('frequency', models.IntegerField(default='2400')),
                ('latency', models.CharField(default='CL11', max_length=10)),
                ('ram_type', models.CharField(default='DDR3', max_length=10)),
            ],
            bases=('products.product',),
        ),
    ]
