# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20170526_1600'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('shipping_address', models.CharField(max_length=200)),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.User')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
