# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('memory', models.IntegerField(default=1000)),
                ('speed', models.IntegerField(default=7200)),
                ('interface', models.CharField(default='SATA3', max_length=20)),
            ],
            bases=('products.product',),
        ),
    ]
